import { useState, useEffect, useCallback } from 'react';
import { toast } from 'react-toastify';
import { notificationApi } from '../../services/api';
import { Loader2, Bell, Check, Calendar } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import websocketService from '../../services/websocketService';

const AdminNotifications = () => {
    const { user } = useAuth();
    const [selectedFilter, setSelectedFilter] = useState('All');
    const [notifications, setNotifications] = useState([]);
    const [loading, setLoading] = useState(true);
    const [wsConnected, setWsConnected] = useState(false);

    const loadNotifications = useCallback(async () => {
        try {
            setLoading(true);
            const response = await notificationApi.getMyNotifications();
            const notificationsData = response.data || [];
            const sorted = notificationsData.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
            setNotifications(sorted);
        } catch (error) {
            console.error('Error loading admin notifications:', error);
            toast.error('Failed to load notifications');
        } finally {
            setLoading(false);
        }
    }, []);

    const markAsRead = async (notificationId) => {
        try {
            console.log('Marking notification as read:', notificationId);

            // Check if this is a temporary ID (from WebSocket notifications)
            // Temporary IDs are generated by Date.now() and are much larger than database IDs
            const isTemporaryId = notificationId > 1000000000000; // Timestamp-like ID

            if (isTemporaryId) {
                // For temporary IDs, just update local state without calling backend
                console.log('Temporary notification ID detected, updating local state only');
                setNotifications(prev => prev.map(n => n.id === notificationId ? { ...n, readFlag: true } : n));
                return;
            }

            // For real database IDs, call the backend
            const response = await notificationApi.markAsRead(notificationId);
            console.log('Mark as read response:', response);

            // Update local state
            setNotifications(prev => prev.map(n => n.id === notificationId ? { ...n, readFlag: true } : n));

            // Force refresh the navbar unread count by triggering a custom event
            window.dispatchEvent(new CustomEvent('refreshUnreadCount'));

            // Reload notifications from server to ensure sync
            setTimeout(() => {
                loadNotifications();
            }, 500);

        } catch (error) {
            console.error('Error marking notification as read:', error);
            toast.error('Failed to mark notification as read');
        }
    };

    const handleWsNotification = useCallback((payload) => {
        // Check if this notification already exists to prevent duplicates
        const notificationContent = payload.message || payload.body || 'You have a new notification.';
        const notificationTitle = payload.title || 'Notification';

        setNotifications(prev => {
            // Check if a notification with the same content already exists
            const exists = prev.some(n =>
                n.body === notificationContent &&
                n.title === notificationTitle &&
                // Check if it was created within the last 5 seconds (to catch duplicates)
                (Date.now() - new Date(n.createdAt).getTime()) < 5000
            );

            if (exists) {
                console.log('🔄 Duplicate notification detected, skipping...');
                return prev;
            }

            // Accept generic notifications
            const formatted = {
                id: Date.now(),
                title: notificationTitle,
                body: notificationContent,
                createdAt: new Date().toISOString(),
                readFlag: false,
                coachNotes: payload.coachNotes,
                rejectionReason: payload.rejectionReason,
            };
            return [formatted, ...prev];
        });
    }, []);

    // Auto mark all as read when component mounts
    useEffect(() => {
        const markAllAsReadOnVisit = async () => {
            try {
                await notificationApi.markAllAsRead();
                console.log('All notifications marked as read on page visit');
                // Force refresh the navbar unread count
                window.dispatchEvent(new CustomEvent('refreshUnreadCount'));
            } catch (error) {
                console.error('Error marking all notifications as read on visit:', error);
            }
        };

        markAllAsReadOnVisit();
    }, []);

    useEffect(() => {
        loadNotifications();
    }, [loadNotifications]);

    useEffect(() => {
        if (user?.token) {
            websocketService.connect(
                user.token,
                () => {
                    setWsConnected(true);
                    // Admin also uses notifications stream
                    websocketService.subscribeToNotifications(user.email, handleWsNotification);
                },
                () => setWsConnected(false)
            );
        }
        return () => {
            websocketService.unsubscribeFromNotifications(user?.email);
        };
    }, [user, handleWsNotification]);

    // Calculate unread count from current notifications
    const unreadCount = notifications.filter(n => !n.readFlag).length;

    const filteredNotifications = selectedFilter === 'All'
        ? notifications
        : notifications.filter(n => selectedFilter === 'Unread' ? !n.readFlag : true);

    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <Loader2 className="w-8 h-8 animate-spin text-[#c53445]" />
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div className="flex items-center space-x-3">
                    <h1 className="text-3xl font-bold text-gray-900">Notifications</h1>
                    {unreadCount > 0 && (
                        <span className="bg-[#c53445] text-white text-sm font-medium px-2 py-1 rounded-full">
                            {unreadCount}
                        </span>
                    )}
                </div>
                <div className="flex space-x-2">
                    <button
                        onClick={() => setSelectedFilter('All')}
                        className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${selectedFilter === 'All' ? 'bg-[#c53445] text-white' : 'bg-white text-gray-700 border border-gray-300 hover:bg-gray-50'}`}
                    >
                        All
                    </button>
                    <button
                        onClick={() => setSelectedFilter('Unread')}
                        className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${selectedFilter === 'Unread' ? 'bg-[#c53445] text-white' : 'bg-white text-gray-700 border border-gray-300 hover:bg-gray-50'}`}
                    >
                        Unread
                    </button>
                </div>
            </div>

            {!wsConnected && (
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3">
                    <div className="flex items-center space-x-2">
                        <Bell className="w-5 h-5 text-yellow-600" />
                        <span className="text-yellow-800 text-sm">Real-time notifications are currently unavailable.</span>
                    </div>
                </div>
            )}

            <div className="space-y-4">
                {filteredNotifications.map((n) => (
                    <div
                        key={n.id}
                        className={`rounded-lg shadow-sm p-6 transition-all duration-200 ${n.readFlag ? 'bg-white border-gray-200 border' : 'bg-[#fdf2f8] border-blue-200 ring-1 ring-[#c53445]'}`}
                    >
                        <div className="flex items-start space-x-4">
                            <div className="flex-shrink-0">
                                <div className="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center">
                                    <i className="fas fa-bell text-lg text-[#c53445]"></i>
                                </div>
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="flex items-start justify-between">
                                    <div className="flex-1">
                                        <h3 className="text-lg font-semibold text-gray-900 mb-2">{n.title || 'Notification'}</h3>
                                        <p className="text-gray-600 font-semibold mb-3 leading-relaxed whitespace-pre-line">{n.body}</p>
                                        {/* Optional extra fields (coach notes / reason) */}
                                        {n.coachNotes && n.coachNotes.trim() && (
                                            <div className="bg-blue-50 border-l-4 border-blue-400 p-3 mb-3">
                                                <p className="text-sm text-blue-800"><strong>Coach's message:</strong> {n.coachNotes}</p>
                                            </div>
                                        )}
                                        {n.rejectionReason && n.rejectionReason.trim() && (
                                            <div className="bg-red-50 border-l-4 border-red-400 p-3 mb-3">
                                                <p className="text-sm text-red-800"><strong>Reason:</strong> {n.rejectionReason}</p>
                                            </div>
                                        )}
                                        <p className="text-sm text-gray-500">{new Date(n.createdAt).toLocaleString()}</p>
                                    </div>
                                    <div className="flex items-center space-x-2 ml-4">
                                        {!n.readFlag && (
                                            <button
                                                onClick={() => markAsRead(n.id)}
                                                className="p-2 text-gray-400 hover:text-green-600 transition-colors"
                                                title="Mark as read"
                                            >
                                                <Check className="w-4 h-4" />
                                            </button>
                                        )}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {filteredNotifications.length === 0 && (
                <div className="text-center py-12">
                    <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                        <Bell className="w-8 h-8 text-gray-400" />
                    </div>
                    <h3 className="text-lg font-medium text-gray-900 mb-2">No notifications</h3>
                    <p className="text-gray-500">You're all caught up.</p>
                </div>
            )}
        </div>
    );
};

export default AdminNotifications;
