import { useState, useEffect, useCallback } from 'react';
import { toast } from 'react-toastify';
import { useAuth } from '../../context/AuthContext';
import { notificationApi } from '../../services/api';
import websocketService from '../../services/websocketService';
import { Loader2, Bell, Check, Trash2 } from 'lucide-react';

const ClientNotifications = () => {
    const { user } = useAuth();
    const [selectedFilter, setSelectedFilter] = useState('All');
    const [notifications, setNotifications] = useState([]);
    const [loading, setLoading] = useState(true);
    const [wsConnected, setWsConnected] = useState(false);
    const [unreadCount, setUnreadCount] = useState(0);

    // Load notifications from API
    const loadNotifications = useCallback(async () => {
        try {
            setLoading(true);
            console.log('Loading notifications...');

            const response = await notificationApi.getMyNotifications();
            const notificationsData = response.data || [];

            console.log('Notifications loaded:', notificationsData);

            // Sort notifications by creation date (newest first)
            const sortedNotifications = notificationsData.sort((a, b) =>
                new Date(b.createdAt) - new Date(a.createdAt)
            );

            setNotifications(sortedNotifications);

            // Calculate unread count
            const unread = notificationsData.filter(n => !n.readFlag).length;
            setUnreadCount(unread);

        } catch (error) {
            console.error('Error loading notifications:', error);
            toast.error('Failed to load notifications');
        } finally {
            setLoading(false);
        }
    }, []);

    // Mark notification as read
    const markAsRead = async (notificationId) => {
        try {
            console.log('Marking notification as read:', notificationId);

            // Check if this is a temporary ID (from WebSocket notifications)
            // Temporary IDs are generated by Date.now() and are much larger than database IDs
            const isTemporaryId = notificationId > 1000000000000; // Timestamp-like ID

            if (isTemporaryId) {
                // For temporary IDs, just update local state without calling backend
                console.log('Temporary notification ID detected, updating local state only');
                setNotifications(prev =>
                    prev.map(n =>
                        n.id === notificationId
                            ? { ...n, readFlag: true }
                            : n
                    )
                );
                setUnreadCount(prev => Math.max(0, prev - 1));
                return;
            }

            // For real database IDs, call the backend
            const response = await notificationApi.markAsRead(notificationId);
            console.log('Mark as read response:', response);

            // Update local state immediately
            setNotifications(prev =>
                prev.map(n =>
                    n.id === notificationId
                        ? { ...n, readFlag: true }
                        : n
                )
            );
            setUnreadCount(prev => Math.max(0, prev - 1));

            // Force refresh the navbar unread count by triggering a custom event
            window.dispatchEvent(new CustomEvent('refreshUnreadCount'));

            // Reload notifications from server to ensure sync
            setTimeout(() => {
                loadNotifications();
            }, 500);

        } catch (error) {
            console.error('Error marking notification as read:', error);
            toast.error('Failed to mark notification as read');
        }
    };

    // Mark all notifications as read
    const markAllAsRead = async () => {
        try {
            await notificationApi.markAllAsRead();

            // Update local state
            setNotifications(prev =>
                prev.map(n => ({ ...n, readFlag: true }))
            );

            setUnreadCount(0);

            // Force refresh the navbar unread count by triggering a custom event
            window.dispatchEvent(new CustomEvent('refreshUnreadCount'));

            // Reload notifications from server to ensure sync
            setTimeout(() => {
                loadNotifications();
            }, 500);

            toast.success('All notifications marked as read');

        } catch (error) {
            console.error('Error marking all notifications as read:', error);
            toast.error('Failed to mark all notifications as read');
        }
    };

    // WebSocket notification handler
    const handleWebSocketNotification = useCallback((newNotification) => {
        console.log('🔔 Received real-time notification:', newNotification);

        // Check if this notification already exists to prevent duplicates
        const notificationContent = newNotification.message || newNotification.body || '';
        const notificationTitle = newNotification.title || getNotificationTitle(newNotification.type);

        setNotifications(prev => {
            // Check if a notification with the same content already exists
            const exists = prev.some(n =>
                n.body === notificationContent &&
                n.title === notificationTitle &&
                // Check if it was created within the last 5 seconds (to catch duplicates)
                (Date.now() - new Date(n.createdAt).getTime()) < 5000
            );

            if (exists) {
                console.log('🔄 Duplicate notification detected, skipping...');
                return prev;
            }

            // Format the notification for display
            const formattedNotification = {
                ...newNotification,
                id: Date.now(), // Generate temporary ID for new notifications
                title: notificationTitle,
                body: notificationContent,
                createdAt: new Date().toISOString(),
                readFlag: false
            };

            // Add new notification to the top of the list
            return [formattedNotification, ...prev];
        });

        // Increment unread count
        setUnreadCount(prev => prev + 1);

        // Show toast notification with deduplication
        // Use a unique key to prevent duplicate toasts
        const toastKey = `notification-${newNotification.type}-${newNotification.bookingId || Date.now()}`;
        toast.info(notificationContent || notificationTitle, {
            position: "top-right",
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: true,
            pauseOnHover: true,
            draggable: true,
            toastId: toastKey, // This prevents duplicate toasts with the same ID
        });
    }, []);

    // Helper function to get notification title based on type
    const getNotificationTitle = (type) => {
        switch (type) {
            case 'MEMBERSHIP_EXPIRATION':
                return 'Membership Expiration Reminder';
            case 'MEMBERSHIP_RENEWED':
                return 'Membership Renewed Successfully';
            case 'BOOKING_ACCEPTED':
                return 'Booking Request Accepted';
            case 'BOOKING_REJECTED':
                return 'Booking Request Rejected';
            default:
                return 'New Notification';
        }
    };

    // Initialize WebSocket connection
    useEffect(() => {
        console.log('🔌 Client Notifications WebSocket useEffect triggered, user:', user);
        if (user?.token) {
            console.log('🚀 Connecting to notification WebSocket...');
            websocketService.connect(
                user.token,
                () => {
                    console.log('✅ Notification WebSocket connected successfully');
                    setWsConnected(true);

                    // Subscribe to notifications
                    websocketService.subscribeToNotifications(user.email, handleWebSocketNotification);
                },
                (error) => {
                    console.error('❌ Notification WebSocket connection failed:', error);
                    setWsConnected(false);
                    toast.error('Real-time notifications unavailable');
                }
            );
        }

        return () => {
            console.log('🔌 Disconnecting notification WebSocket...');
            websocketService.unsubscribeFromNotifications(user?.email);
        };
    }, [user, handleWebSocketNotification]);

    // Load notifications on component mount
    useEffect(() => {
        loadNotifications();
    }, [loadNotifications]);

    // Filter notifications based on selected filter
    const filteredNotifications = selectedFilter === 'All'
        ? notifications
        : notifications.filter(notification =>
            selectedFilter === 'Unread' ? !notification.readFlag : true
        );

    // Get notification icon based on type
    const getNotificationIcon = (notification) => {
        const type = notification.type || 'GENERAL';

        switch (type) {
            case 'MEMBERSHIP_EXPIRATION':
                return 'fas fa-exclamation-triangle text-orange-500';
            case 'MEMBERSHIP_RENEWED':
                return 'fas fa-check-circle text-green-500';
            case 'BOOKING_ACCEPTED':
                return 'fas fa-calendar-check text-blue-500';
            case 'BOOKING_REJECTED':
                return 'fas fa-calendar-times text-red-500';
            default:
                return 'fas fa-bell text-gray-500';
        }
    };

    // Get notification background color
    const getNotificationBgColor = (notification) => {
        if (notification.readFlag) {
            return 'bg-white border-gray-200 border';
        }

        const type = notification.type || 'GENERAL';
        switch (type) {
            case 'MEMBERSHIP_EXPIRATION':
                return 'bg-orange-50 border-orange-200';
            case 'MEMBERSHIP_RENEWED':
                return 'bg-green-50 border-green-200';
            case 'BOOKING_ACCEPTED':
                return 'bg-blue-50 border-blue-200';
            case 'BOOKING_REJECTED':
                return 'bg-red-50 border-red-200';
            default:
                return 'bg-red-50 border-blue-200';
        }
    };

    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <Loader2 className="w-8 h-8 animate-spin text-[#c53445]" />
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex justify-between items-center">
                <div className="flex items-center space-x-3">
                    <h1 className="text-3xl font-bold text-gray-900">Notifications</h1>
                    {unreadCount > 0 && (
                        <span className="bg-[#c53445] text-white text-sm font-medium px-2 py-1 rounded-full">
                            {unreadCount}
                        </span>
                    )}
                </div>

                {/* Filter Buttons */}
                <div className="flex space-x-2">
                    <button
                        onClick={() => setSelectedFilter('All')}
                        className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${selectedFilter === 'All'
                            ? 'bg-[#c53445] text-white'
                            : 'bg-white text-gray-700 border border-gray-300 hover:bg-gray-50'
                            }`}
                    >
                        All
                    </button>
                    <button
                        onClick={() => setSelectedFilter('Unread')}
                        className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${selectedFilter === 'Unread'
                            ? 'bg-[#c53445] text-white'
                            : 'bg-white text-gray-700 border border-gray-300 hover:bg-gray-50'
                            }`}
                    >
                        Unread
                    </button>
                    {unreadCount > 0 && (
                        <button
                            onClick={markAllAsRead}
                            className="px-4 py-2 bg-green-600 text-white rounded-lg text-sm font-medium hover:bg-green-700 transition-colors flex items-center space-x-2"
                        >
                            <Check className="w-4 h-4" />
                            <span>Mark All Read</span>
                        </button>
                    )}
                </div>
            </div>

            {/* WebSocket Status */}
            {!wsConnected && (
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3">
                    <div className="flex items-center space-x-2">
                        <Bell className="w-5 h-5 text-yellow-600" />
                        <span className="text-yellow-800 text-sm">
                            Real-time notifications are currently unavailable. Notifications will update when you refresh the page.
                        </span>
                    </div>
                </div>
            )}

            {/* Notifications List */}
            <div className="space-y-4">
                {filteredNotifications.map((notification) => (
                    <div
                        key={notification.id}
                        className={`rounded-lg shadow-sm  p-6 transition-all duration-200 ${getNotificationBgColor(notification)
                            } ${!notification.readFlag ? 'ring-1 ring-[#c53445]' : ''}`}
                    >
                        <div className="flex items-start space-x-4">
                            {/* Icon */}
                            <div className="flex-shrink-0">
                                <div className="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center">
                                    <i className={`${getNotificationIcon(notification)} text-lg`}></i>
                                </div>
                            </div>

                            {/* Content */}
                            <div className="flex-1 min-w-0">
                                <div className="flex items-start justify-between">
                                    <div className="flex-1">
                                        <h3 className="text-lg font-semibold text-gray-900 mb-2">
                                            {notification.title}
                                        </h3>
                                        <p className="text-gray-600 mb-3 leading-relaxed whitespace-pre-line">
                                            {notification.body}
                                        </p>

                                        {/* Show coach notes for booking acceptance */}
                                        {notification.coachNotes && notification.coachNotes.trim() && (
                                            <div className="bg-blue-50 border-l-4 border-blue-400 p-3 mb-3">
                                                <p className="text-sm text-blue-800">
                                                    <strong>Coach's message:</strong> {notification.coachNotes}
                                                </p>
                                            </div>
                                        )}

                                        {/* Show rejection reason for booking rejection */}
                                        {notification.rejectionReason && notification.rejectionReason.trim() && (
                                            <div className="bg-red-50 border-l-4 border-red-400 p-3 mb-3">
                                                <p className="text-sm text-red-800">
                                                    <strong>Reason:</strong> {notification.rejectionReason}
                                                </p>
                                            </div>
                                        )}

                                        <p className="text-sm text-gray-500">
                                            {new Date(notification.createdAt).toLocaleString()}
                                        </p>
                                    </div>

                                    {/* Actions */}
                                    <div className="flex items-center space-x-2 ml-4">
                                        {!notification.readFlag && (
                                            <button
                                                onClick={() => markAsRead(notification.id)}
                                                className="p-2 text-gray-400 hover:text-green-600 transition-colors"
                                                title="Mark as read"
                                            >
                                                <Check className="w-4 h-4" />
                                            </button>
                                        )}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Empty State */}
            {filteredNotifications.length === 0 && (
                <div className="text-center py-12">
                    <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                        <Bell className="w-8 h-8 text-gray-400" />
                    </div>
                    <h3 className="text-lg font-medium text-gray-900 mb-2">No notifications</h3>
                    <p className="text-gray-500">
                        {selectedFilter === 'Unread'
                            ? 'You\'re all caught up! No unread notifications.'
                            : 'You don\'t have any notifications yet.'
                        }
                    </p>
                </div>
            )}
        </div>
    );
};

export default ClientNotifications;
